theme: jekyll-theme-cayman

title: [Simpli Weather]
description: [Simpli Weather is a simple weather app, with everything you may need, without the ads. This app was developed to be an alternative to other apps with advertisements.]


show_downloads: [true]
